# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plantilla.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt4agg import NavigationToolbar2QT as NavigationToolbar


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.plane_of = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plane_of.setFont(font)
        self.plane_of.setObjectName(_fromUtf8("plane_of"))
        self.horizontalLayout.addWidget(self.plane_of)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout_12.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.perito = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.perito.setFont(font)
        self.perito.setObjectName(_fromUtf8("perito"))
        self.horizontalLayout_2.addWidget(self.perito)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.possession = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.possession.setFont(font)
        self.possession.setObjectName(_fromUtf8("possession"))
        self.horizontalLayout_3.addWidget(self.possession)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.homeowner = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.homeowner.setFont(font)
        self.homeowner.setObjectName(_fromUtf8("homeowner"))
        self.horizontalLayout_4.addWidget(self.homeowner)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.location = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.location.setFont(font)
        self.location.setObjectName(_fromUtf8("location"))
        self.horizontalLayout_5.addWidget(self.location)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.date = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date.setFont(font)
        self.date.setObjectName(_fromUtf8("date"))
        self.horizontalLayout_6.addWidget(self.date)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        # Table Result and graph
        self.figure = plt.figure(figsize=(3, 3))
        self.canvas = FigureCanvas(self.figure)
        self.toolbarGraph = NavigationToolbar(self.canvas, self.centralwidget)
        self.verticalLayoutGraph = QtGui.QVBoxLayout()
        self.verticalLayoutGraph.setObjectName(_fromUtf8("verticalGraph"))
        self.verticalLayoutGraph.addWidget(self.toolbarGraph)
        self.verticalLayoutGraph.addWidget(self.canvas)
        self.horizontalLayoutGraph = QtGui.QHBoxLayout()
        self.verticalLayoutGraph.setObjectName(_fromUtf8("horizontalGraph"))
        self.tableResult = QtGui.QTableWidget(self.centralwidget)
        self.tableResult.setObjectName(_fromUtf8("tableResult"))
        self.tableResult.setColumnCount(0)
        self.tableResult.setRowCount(0)
        self.horizontalLayoutGraph.addWidget(self.tableResult)
        self.horizontalLayoutGraph.addLayout(self.verticalLayoutGraph)
        self.verticalLayout.addLayout(self.horizontalLayoutGraph)
        # self.verticalLayout.addWidget(self.tableResult)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.calcBtn = QtGui.QPushButton(self.centralwidget)
        self.calcBtn.setObjectName(_fromUtf8("calcBtn"))
        self.horizontalLayout_7.addWidget(self.calcBtn)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.label_sumAngs = QtGui.QLabel(self.centralwidget)
        self.label_sumAngs.setObjectName(_fromUtf8("label_sumAngs"))
        self.horizontalLayout_8.addWidget(self.label_sumAngs)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.label_perim = QtGui.QLabel(self.centralwidget)
        self.label_perim.setObjectName(_fromUtf8("label_perim"))
        self.horizontalLayout_9.addWidget(self.label_perim)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.label_area = QtGui.QLabel(self.centralwidget)
        self.label_area.setObjectName(_fromUtf8("label_area"))
        self.horizontalLayout_10.addWidget(self.label_area)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.tableResult.raise_()
        self.label.raise_()
        self.plane_of.raise_()
        self.label_3.raise_()
        self.location.raise_()
        self.label_5.raise_()
        self.perito.raise_()
        self.label_7.raise_()
        self.possession.raise_()
        self.label_9.raise_()
        self.homeowner.raise_()
        self.label_11.raise_()
        self.date.raise_()
        self.label_11.raise_()
        self.calcBtn.raise_()
        self.perito.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label_sumAngs.raise_()
        self.label_6.raise_()
        self.label_perim.raise_()
        self.label_10.raise_()
        self.label_area.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 738, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/new-file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionEdit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/edit-file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit.setIcon(icon1)
        self.actionEdit.setObjectName(_fromUtf8("actionEdit"))
        self.actionToPdf = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/pdf.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionToPdf.setIcon(icon2)
        self.actionToPdf.setObjectName(_fromUtf8("actionToPdf"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/floppy-128.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/save_as-128.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_as.setIcon(icon4)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionOpen = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/open-file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon5)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.menuArchivo.addAction(self.actionNew)
        self.menuArchivo.addAction(self.actionOpen)
        self.menuArchivo.addAction(self.actionSave)
        self.menuArchivo.addAction(self.actionSave_as)
        self.menuArchivo.addAction(self.actionToPdf)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addAction(self.actionToPdf)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Planilla de cálculo de coordenadas y superficie", None))
        self.label.setText(_translate("MainWindow", "Plano de:", None))
        self.plane_of.setText(_translate("MainWindow", "-", None))
        self.label_5.setText(_translate("MainWindow", "Perito:", None))
        self.perito.setText(_translate("MainWindow", "Ing. COPA, Rodi Alfredo", None))
        self.label_7.setText(_translate("MainWindow", "Propiedad:", None))
        self.possession.setText(_translate("MainWindow", "-", None))
        self.label_9.setText(_translate("MainWindow", "Propietario:", None))
        self.homeowner.setText(_translate("MainWindow", "-", None))
        self.label_3.setText(_translate("MainWindow", "Ubicación:", None))
        self.location.setText(_translate("MainWindow", "-", None))
        self.label_11.setText(_translate("MainWindow", "Fecha:", None))
        self.date.setText(_translate("MainWindow", "-", None))
        self.calcBtn.setText(_translate("MainWindow", "Calcular", None))
        self.label_2.setText(_translate("MainWindow", "Suma de ángulos:", None))
        self.label_sumAngs.setText(_translate("MainWindow", "-", None))
        self.label_6.setText(_translate("MainWindow", "Perímetro:", None))
        self.label_perim.setText(_translate("MainWindow", "-", None))
        self.label_10.setText(_translate("MainWindow", "Superficie:", None))
        self.label_area.setText(_translate("MainWindow", "-", None))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionNew.setText(_translate("MainWindow", "Nuevo", None))
        self.actionNew.setToolTip(_translate("MainWindow", "Nuevo", None))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionEdit.setText(_translate("MainWindow", "Editar", None))
        self.actionEdit.setToolTip(_translate("MainWindow", "Editar", None))
        self.actionToPdf.setText(_translate("MainWindow", "Exportar a pdf", None))
        self.actionToPdf.setToolTip(_translate("MainWindow", "Exportar a pdf", None))
        self.actionSave.setText(_translate("MainWindow", "Guardar", None))
        self.actionSave.setToolTip(_translate("MainWindow", "Guardar", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+G", None))
        self.actionSave_as.setText(_translate("MainWindow", "Guardar como", None))
        self.actionSave_as.setToolTip(_translate("MainWindow", "Guardaar archivo como", None))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+G", None))
        self.actionOpen.setText(_translate("MainWindow", "Abrir", None))
        self.actionOpen.setToolTip(_translate("MainWindow", "Abrir archivo", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))

import icons_rc
